language: node_js
node_js:
- "stable"
install:
  - npm install
services:
  - postgresql
script:
  - npm test
env:
  - NODE_ENV=test
cache:
  directories:
    - "node_modules"
before_script:
  - createuser olubori -s -U postgres
  - createdb traka_test --username=olubori
after_success :
  - npm run coverage
